name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Sæt op JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Byg og test med Maven
        run: mvn clean install

      - name: Kør Qodana
        uses: JetBrains/qodana-action@v2023.2
        with:
          args: --baseline

      - name: Deploy (valgfrit, fx Docker)
        run: |
          echo "Her kan du indsætte deploy-scripts, fx Docker eller en server"
