name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Tjek ud koden fra GitHub
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # Installer afhængigheder og kør test
      - name: Build with Maven
        run: mvn clean install


      # Upload testresultater
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/test-classes

      - name: Upload Qodana report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qodana-report
          path: .qodana
